<<<<<<< HEAD
name: collagen-des 
channels: 
  - conda-forge 
  - defaults 
dependencies: 
  - python=3.11 
  - pandas 
  - numpy 
  - scikit-learn 
  - tensorflow=2.16 
  - rdkit=2024.09.1 
  - jupyter 
  - matplotlib 
  - seaborn 
  - shap 
  - xgboost 
  - openpyxl 
  - tqdm 
  - pip 
  - pip: 
    - molvs 
    - biopython 
=======
name: collagen-des
channels:
  - conda-forge
dependencies:
  - python=3.11
  - rdkit=2024.09.1
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - jupyterlab
  - scikit-learn
  - tensorflow
  - xgboost
  - shap
  - openpyxl
>>>>>>> 631d06300582f096b508eba87ffae7024c28b68e
